# -*- coding: utf-8 -*-

# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MUSCATDialog(object):
    def setupUi(self, MUSCATDialog):
        MUSCATDialog.setObjectName("MUSCATDialog")
        MUSCATDialog.resize(480, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(MUSCATDialog)
        self.verticalLayout.setObjectName("verticalLayout")

        # Initial (T0)
        self.layout_initial = QtWidgets.QHBoxLayout()
        self.layout_initial.setObjectName("layout_initial")
        self.labelInitial = QtWidgets.QLabel(MUSCATDialog)
        self.labelInitial.setObjectName("labelInitial")
        self.layout_initial.addWidget(self.labelInitial)
        self.lineInitial = QtWidgets.QLineEdit(MUSCATDialog)
        self.lineInitial.setObjectName("lineInitial")
        self.layout_initial.addWidget(self.lineInitial)
        self.btnBrowseInitial = QtWidgets.QPushButton(MUSCATDialog)
        self.btnBrowseInitial.setObjectName("btnBrowseInitial")
        self.layout_initial.addWidget(self.btnBrowseInitial)
        self.verticalLayout.addLayout(self.layout_initial)

        # Final (T1)
        self.layout_final = QtWidgets.QHBoxLayout()
        self.layout_final.setObjectName("layout_final")
        self.labelFinal = QtWidgets.QLabel(MUSCATDialog)
        self.labelFinal.setObjectName("labelFinal")
        self.layout_final.addWidget(self.labelFinal)
        self.lineFinal = QtWidgets.QLineEdit(MUSCATDialog)
        self.lineFinal.setObjectName("lineFinal")
        self.layout_final.addWidget(self.lineFinal)
        self.btnBrowseFinal = QtWidgets.QPushButton(MUSCATDialog)
        self.btnBrowseFinal.setObjectName("btnBrowseFinal")
        self.layout_final.addWidget(self.btnBrowseFinal)
        self.verticalLayout.addLayout(self.layout_final)

        # Output
        self.layout_out = QtWidgets.QHBoxLayout()
        self.layout_out.setObjectName("layout_out")
        self.labelOutput = QtWidgets.QLabel(MUSCATDialog)
        self.labelOutput.setObjectName("labelOutput")
        self.layout_out.addWidget(self.labelOutput)
        self.lineOut = QtWidgets.QLineEdit(MUSCATDialog)
        self.lineOut.setObjectName("lineOut")
        self.layout_out.addWidget(self.lineOut)
        self.btnBrowseOut = QtWidgets.QPushButton(MUSCATDialog)
        self.btnBrowseOut.setObjectName("btnBrowseOut")
        self.layout_out.addWidget(self.btnBrowseOut)
        self.verticalLayout.addLayout(self.layout_out)

        # Steps
        self.layout_steps = QtWidgets.QHBoxLayout()
        self.layout_steps.setObjectName("layout_steps")
        self.labelSteps = QtWidgets.QLabel(MUSCATDialog)
        self.labelSteps.setObjectName("labelSteps")
        self.layout_steps.addWidget(self.labelSteps)
        self.spinSteps = QtWidgets.QSpinBox(MUSCATDialog)
        self.spinSteps.setMinimum(1)
        self.spinSteps.setMaximum(50)
        self.spinSteps.setProperty("value", 1)
        self.spinSteps.setObjectName("spinSteps")
        self.layout_steps.addWidget(self.spinSteps)
        self.verticalLayout.addLayout(self.layout_steps)

        # Spatial Variables
        self.btnAddDriver = QtWidgets.QPushButton(MUSCATDialog)
        self.btnAddDriver.setObjectName("btnAddDriver")
        self.verticalLayout.addWidget(self.btnAddDriver)
        self.textDrivers = QtWidgets.QTextEdit(MUSCATDialog)
        self.textDrivers.setObjectName("textDrivers")
        self.verticalLayout.addWidget(self.textDrivers)

        # Run Mode + Run
        self.layout_run = QtWidgets.QHBoxLayout()
        self.layout_run.setObjectName("layout_run")
        self.comboRunMode = QtWidgets.QComboBox(MUSCATDialog)
        self.comboRunMode.setObjectName("comboRunMode")
        self.comboRunMode.addItem("")
        self.comboRunMode.addItem("")
        self.layout_run.addWidget(self.comboRunMode)
        self.btnRun = QtWidgets.QPushButton(MUSCATDialog)
        self.btnRun.setObjectName("btnRun")
        self.layout_run.addWidget(self.btnRun)
        self.verticalLayout.addLayout(self.layout_run)

        # Progress Bar
        self.progressBar = QtWidgets.QProgressBar(MUSCATDialog)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setValue(0)
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(MUSCATDialog)
        QtCore.QMetaObject.connectSlotsByName(MUSCATDialog)

    def retranslateUi(self, MUSCATDialog):
        _translate = QtCore.QCoreApplication.translate
        MUSCATDialog.setWindowTitle(_translate("MUSCATDialog", "MUSCAT - Markov-based Urban Simulation and Change Analysis Tool"))
        self.labelInitial.setText(_translate("MUSCATDialog", "Initial Map (T0):"))
        self.btnBrowseInitial.setText(_translate("MUSCATDialog", "Browse"))
        self.labelFinal.setText(_translate("MUSCATDialog", "Final Map (T1):"))
        self.btnBrowseFinal.setText(_translate("MUSCATDialog", "Browse"))
        self.labelOutput.setText(_translate("MUSCATDialog", "Output Path:"))
        self.btnBrowseOut.setText(_translate("MUSCATDialog", "Save As"))
        self.labelSteps.setText(_translate("MUSCATDialog", "Simulation Steps:"))
        self.btnAddDriver.setText(_translate("MUSCATDialog", "Add Spatial Variable"))
        self.textDrivers.setPlaceholderText(_translate("MUSCATDialog", "List of added spatial variables will appear here..."))
        self.comboRunMode.setItemText(0, _translate("MUSCATDialog", "Run Simulation"))
        self.comboRunMode.setItemText(1, _translate("MUSCATDialog", "Validate"))
        self.btnRun.setText(_translate("MUSCATDialog", "Run"))
